name: Feature Pipeline

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Test Workflow
        run: echo "Workflow is working successfully"
