name: Feature Pipeline

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  export-solution:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Power Platform CLI
        uses: microsoft/powerplatform-actions/actions-install@v1

      - name: Authenticate
        run: |
          pac auth create \
            --applicationId ${{ secrets.POWERPLATFORM_APP_ID }} \
            --clientSecret ${{ secrets.POWERPLATFORM_CLIENT_SECRET }} \
            --tenant ${{ secrets.POWERPLATFORM_TENANT_ID }} \
            --environment ${{ secrets.DEV_ENV_URL }}

      - name: Verify Authentication
        run: pac auth list

      - name: Export Unmanaged Solution
        run: |
          pac solution export \
          --name YOUR_SOLUTION_UNIQUE_NAME \
          --path Solution.zip \
          --managed false

      - name: Create Folder
        run: |
          mkdir -p Solutions/Unmanaged/YOUR_SOLUTION_UNIQUE_NAME

      - name: Unpack Solution
        run: |
          pac solution unpack \
          --zipfile Solution.zip \
          --folder Solutions/Unmanaged/YOUR_SOLUTION_UNIQUE_NAME \
          --packagetype Both

      - name: Commit Changes
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

          git add .

          git commit -m "Export latest solution" || echo "No changes"

          git push
